name: CustomSoundLib
version: 1.1
main: io.github.lumine1909.core.CustomSoundLib
api-version: 1.13
authors:
  - Lumine1909
commands:
  customsoundlib:
    aliases:
      - csl
permissions:
  customsoundlib.reload:
    default: op